apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bbooker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ndaden/bbooker.git
    targetRevision: main
    path: infra/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: bbooker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
